remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Final Project for MISY225]
description: [An analytics app based on the Chicago crime dataset]